// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dump_json_ast
Rcpp::String dump_json_ast(Rcpp::String graph);
RcppExport SEXP graphql_dump_json_ast(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(dump_json_ast(graph));
    return rcpp_result_gen;
END_RCPP
}
// dump_schema_json_ast
Rcpp::String dump_schema_json_ast(Rcpp::String graph);
RcppExport SEXP graphql_dump_schema_json_ast(SEXP graphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type graph(graphSEXP);
    rcpp_result_gen = Rcpp::wrap(dump_schema_json_ast(graph));
    return rcpp_result_gen;
END_RCPP
}
